addSbtPlugin("org.typelevel"   % "sbt-tpolecat"    % "0.5.0")
addSbtPlugin("io.spray"        % "sbt-revolver"    % "0.10.0")
addSbtPlugin("com.eed3si9n"    % "sbt-assembly"    % "2.1.5")
addSbtPlugin("org.scalameta"   % "sbt-scalafmt"    % "2.5.2")
addSbtPlugin("ch.epfl.scala"   % "sbt-scalafix"    % "0.14.3")
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "3.3.4")
